# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.3"
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.provision "shell", path: "bootstrap.sh"
end
